model_list:
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY
      vertex_ai_project: os.environ/GOOGLE_CLOUD_PROJECT
      vertex_ai_location: os.environ/GOOGLE_CLOUD_LOCATION

  - model_name: gpt-oss-120b
    litellm_params:
      model: vertex_ai/openai/gpt-oss-120b
      api_key: os.environ/GEMINI_API_KEY
      reasoning_effort: "low"  # Options: "minimal", "low", "medium", "high"
      vertex_ai_project: os.environ/GOOGLE_CLOUD_PROJECT
      vertex_ai_location: os.environ/GOOGLE_CLOUD_LOCATION

  - model_name: gpt-oss-20b-maas
    litellm_params:
      model: vertex_ai/openai/gpt-oss-20b-maas
      api_key: os.environ/GEMINI_API_KEY
      reasoning_effort: "low"  # Options: "minimal", "low", "medium", "high"
      vertex_ai_project: os.environ/GOOGLE_CLOUD_PROJECT
      vertex_ai_location: os.environ/GOOGLE_CLOUD_LOCATION

  - model_name: gemini-2.0-flash-lite
    litellm_params:
      model: gemini/gemini-2.0-flash-lite
      api_key: os.environ/GEMINI_API_KEY
      vertex_ai_project: os.environ/GOOGLE_CLOUD_PROJECT
      vertex_ai_location: os.environ/GOOGLE_CLOUD_LOCATION

litellm_settings:
  drop_params: True
