[project]
name = "movie-guru-ax-subagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "a2a-sdk>=0.3.9",
    "click>=8.3.0",
    "google-adk",
    "opentelemetry-instrumentation-starlette>=0.58b0",
]
